apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

namespace: helloworld

commonLabels:
  app: hello

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- configMap.yaml
- route.yaml
