apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: the-route
  annotations:
    link.argocd.argoproj.io/external-link: http://helloworld-kustomize.apps-crc.testing
spec:
  host: helloworld-kustomize.apps-crc.testing
  port:
    targetPort: 8080
  to:
    kind: Service
    name: the-service
    weight: 100
  wildcardPolicy: None
