apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "helloworld.metadataName" . }}
  labels:
    {{- include "helloworld.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "helloworld.annotations" . | nindent 4 }}
  {{- end }}
data:
  altGreeting: "{{ .Values.greetingMessage }}"
  enableRisky: "{{ .Values.riskyFeature }}"
